# Generated by Django 2.0.2 on 2020-03-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200301_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_id',
            field=models.CharField(default='', max_length=50, verbose_name='图片id'),
        ),
    ]
